spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: Ashi@1234
    
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


 

#JPA Settings
  jpa.hibernate.ddl_auto: create